---
# file: roles/nginx/tasks/main.yml

# Section of installation.
- include: distributions/redhat/main.yml
  when: ansible_os_family == 'RedHat'

# Section of configuration.
- name: Define configuration of nginx.
  template: src=config/nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=root group=root mode=0644
  notify:
    - reload nginx
  become: yes

- name: Define virtual hosts.
  template: src=config/default.conf.j2 dest=/etc/nginx/conf.d/default.conf owner=root group=root mode=0644
  notify:
    - reload nginx
  become: yes

- name: Check nginx has started and enabled to start at boot.
  service: name=nginx state=started enabled=yes
  become: yes
