---
# file: roles/common/tasks/distributions/redhat/main.yml
- name: Install epel repository from yum
  yum: name=epel-release state=present
  become_user: "{{ host.become_user }}"
  become: "{{ host.become }}"

- name: Install necessary packages from yum
  yum: name={{ item }} state=present
  with_items:
    - wget
    - vim
    - libselinux-python
    - gcc
    - gcc-c++
    - perl
    - git
  become_user: "{{ host.become_user }}"
  become: "{{ host.become }}"
