---
# file: roles/common/tasks/distributions/redhat/main.yml
- name: Install epel repository from yum.
  yum: name=epel-release state=present
  become: yes

- name: Install necessary packages from yum.
  yum: name={{item}} state=present
  with_items:
    - vim
    - libselinux-python
    - gcc
    - gcc-c++
    - git
  become: yes
