---
# file: roles/nfs/tasks/main.yml

# Section of installation.
- include: distributions/redhat/main.yml
  when: ansible_os_family == 'RedHat'

# Section of configuration.
- name: Create directory of nfs if not exists
  file: path=/var/nfs state=directory owner=root group=root mode=0755
  become_user: "{{ host.become_user }}"
  become: "{{ host.become }}"

- name: Check if rpcbind has started and enabled to start at boot
  service: name=rpcbind state=started enabled=yes
  become_user: "{{ host.become_user }}"
  become: "{{ host.become }}"

- name: Check if nfs has started and enabled to start at boot
  service: name=nfs state=started enabled=yes
  become_user: "{{ host.become_user }}"
  become: "{{ host.become }}"

- name: Configure nfs
  template: src=config/nfs.j2 dest=/etc/sysconfig/nfs owner=root group=root mode=0644
  notify:
    - Restart nfs
  become_user: "{{ host.become_user }}"
  become: "{{ host.become }}"
