---
# file: roles/php-virtualenv/tasks/main.yml

# Section of installation.
- include: distributions/redhat/main.yml
  when: ansible_os_family == 'RedHat'

# Section of configuration.
- name: Configure bashrc for phpbrew
  shell: /usr/local/bin/phpbrew init &&
         echo "" >> $HOME/.bashrc &&
         echo "# Source PHPbrew" >> $HOME/.bashrc &&
         echo "export PHPBREW_SET_PROMPT=1" >> $HOME/.bashrc &&
         echo "export PHPBREW_BIN=~/.phpbrew/bin" >> $HOME/.bashrc &&
         echo "export PHPBREW_HOME=~/.phpbrew" >> $HOME/.bashrc &&
         echo "export PHPBREW_ROOT=~/.phpbrew" >> $HOME/.bashrc &&
         echo "[[ -e ~/.phpbrew/bashrc ]] && source ~/.phpbrew/bashrc" >> $HOME/.bashrc
  become_user: "{{ phpbrew.become_user }}"
  become: "{{ phpbrew.become }}"

- name: Build virtual environment for php
  shell: source $HOME/.bashrc &&
         /usr/local/bin/phpbrew install "{{ phpbrew.php.version }}" +default +everything -- --with-icu-dir=/usr --with-gd --with-jpeg-dir=/usr/lib64 --with-png-dir=/usr/png --enable-gd-jis-conv &&
         /usr/local/bin/phpbrew switch "{{ phpbrew.php.version }}" &&
         /usr/local/bin/virtphp create --php-bin-dir=$HOME/.phpbrew/php/php-"{{ phpbrew.php.version }}"/bin "{{ virtphp.env.name }}" &&
         echo '' >> $HOME/.bashrc &&
         echo '# Source virtPHP' >> $HOME/.bashrc &&
         echo '[[ -e ~/.virtphp/envs/"{{ virtphp.env.name }}" ]] && source ~/.virtphp/envs/"{{ virtphp.env.name }}"/bin/activate' >> $HOME/.bashrc &&
         echo '' >> $HOME/.bashrc
  become_user: "{{ virtphp.become_user }}"
  become: "{{ virtphp.become }}"
