---
# file: roles/nfs/tasks/distributions/redhat/main.yml

- name: Install necessary packages from yum.
  yum: name={{item}} state=present
  with_items:
    - rpcbind
    - nfs-utils
  become: yes

- name: Configure share directory.
  template: src=config/exports.j2 dest=/etc/exports owner=root group=root mode=0644
  become: yes

- name: Reflect configuration of share directory.
  shell: exportfs -a
  become: yes
