---
# file: roles/php-virtualenv/tasks/distributions/redhat/main.yml

- name: Install necessary packages from yum.
  yum: name={{item}} state=present
  with_items:
  - readline-devel
  - libxml2
  - libxml2-devel
  - libxslt-devel
  - openssl-devel
  - libmcrypt
  - libmcrypt-devel
  - postgresql-devel
  - libicu
  - libicu-devel
  - libmcrypt
  - libmcrypt-devel
  - lcov
  - gmp-devel
  - libcurl-devel
  - libtidy
  - libtidy-devel
  - bzip2-devel
  - libpng
  - libpng-devel
  - libjpeg
  - libjpeg-devel
  - libsmbclient
  - libsmbclient-devel
  - php
  become: yes

- name: Remove symbolic link for libssl.
  file: name=/usr/lib/libssl.so state=absent
  become: yes

- name: Create symbolic link for libssl.
  file: src=/usr/lib64/libssl.so dest=/usr/lib/libssl.so owner=root group=root state=link
  become: yes

- name: Install virtphp.
  shell: cd /tmp &&
         curl -L -O https://github.com/virtphp/virtphp/releases/download/v0.5.2-alpha/virtphp.phar &&
         chmod a+x virtphp.phar &&
         mv virtphp.phar /usr/local/bin/virtphp
  become: yes

- name: Install phpbrew.
  shell: cd /tmp &&
         wget https://github.com/phpbrew/phpbrew/archive/1.20.6.tar.gz &&
         tar xvzf 1.20.6.tar.gz &&
         cd phpbrew-1.20.6 &&
         chmod a+x phpbrew &&
         mv phpbrew /usr/local/bin/ &&
         cd /tmp &&
         rm -rf phpbrew-1.20.6 &&
         rm -f 1.20.6.tar.gz
  become: yes
